### ISSUE TITLE
some questions around visualisation

### ISSUE THREAD

**Issue by jonathanblaney** [SASDigitalHumanitiesTraining/Visualisation#1]
These are some questions which can help focus reactions to a visualisation:
* What cognitive and/or affective effect does this visualization have on you as a viewer/reader?
* How do you think that effect differs from reading the same data in other forms (e.g. as text or in a spreadsheet)?
* Can you imagine other ways this data could be visualised that would be more/less effective?
* What do you imagine is the intent of the creator of the visualisation by presenting the data in this way?

**Comment by soneill-language-arts** [comment]
In response to the W.E.B. Du Bois Paris Exposition:

I don't know the context of this visualisation, and have chosen not to research that just now, as it seems to be deliberately not included in the graphic.

Devoid of context, this visualisation raises for me as a viewer more questions about the data than it answers.
This forces me to begin to interpret for myself, and not rely on a "self-evident" interpretation ostensibly provided by the composer (who I would refer to in this instance as "artist"). For example, what do the colours represent? What does the trajectory of the shape represent? Why does it spiral and zigzag upwards, then flatten out? Is that even the intended directionality, or should I read it from top to bottom?

I imagine the data interpreted in other ways, e.g. a bar chart or piechart, would have much more explanative power, but shift the onus of interpretation away from the viewer. I imagine Du Bois intends to challenge his viewers to provide their own explanations/interpretations for this visualisation.

**Comment by jlvenner** [comment]
Hi! Jess here. 

In response to Soneill:
I too avoided looking at the context of this at first (though I have since done this and found a completely new reading of this visualisation). Before this, however, I has the following thoughts...

The spiral, representing the greatest body of the total black population here encapsulated appears to be a deliberate reference to the inclusivity of country and village living, perhaps in relation to tribal living. (Given the title of exposition, I'm guessing this was part of the exhibitions popular in the late nineteenth and early twentieth century, and so a current or very recent experience of slavery is likely). This is in contrast to the smaller numbers of the total population living in urban settings. The abrupt jutting upwards of the yellow, blue and green lines suggests to me a displacement of individuals from country living, the latter of which is where individuals are more likely to be 'encircled' by other individuals from their own ethnic community. 

Extra reading has presented the added viewpoint of a take on tribal art to visualise this data, and the others like it, from the exposition. 

In reference to the Climate Spiral, I had a few questions: Where is this data in relation to? What should the temperature be? We have no comparative data here, apart from the data itself. Should we assume, because the creator has said so, that the climate in 1880 is an ideal baseline from which to compare the rest of the data? I think this is a good example of when data needs to be 'humanised'. What are the factors that are increasing this over time? Is there any data that we may overlay to make these increases in temperature more accountable?

**Comment by EmmaGrootveld** [comment]
Hi!
Interesting interpretations, Jess and Soneill (is that Sarah?). 
In reference to the Climate Spiral, I think indeed that the 1880 is the point of reference, but the creator doesn't say why he chose that date (perhaps just for practical reasons?). Besides, where do the data come from?

I have similar questions about slate.com. 
Concerning the data: has this map been created with the collaboration and credits of the dataset collectors of “slavevoyages.org”? 
The comment claims that "Of the more than 10 million enslaved Africans to eventually reach the Western Hemisphere, just 388,747—less than 4 percent of the total—came to North America. This was dwarfed by the 1.3 million brought to Spanish Central America, the 4 million brought to British, French, Dutch, and Danish holdings in the Caribbean, and the 4.8 million brought to Brazil." But has the slave trade between the Caribbean+Brazil and North-America been taken into account? As far as I could see this doesn't appear in the map. (Apart from that I was quite shocked by this dehumanizing comment: what do they mean by “just”? We are still talking about 388,747 lives.) 
Concerning the visualization itself: aren't the borders of the countries anachronistic? 
The flows are very fast. It would perhaps be more effective if the areas lit up according to the trade intensity in a certain period of time.

**Comment by Ellis307** [comment]
Hello! I've also had some thoughts on the visualisations. I mainly looked at the firsts one in the list - Slate's slave trade visualisation. I thought it was very effective in the same way as the migrant visualisation. It portrays their interpretation of a ‘crisis’ in a very explicit and alarming manner to a modern audience, though with little nuance. I can't be sure that it was deliberate, but the visualisation had so many moving parts that in some points my laptop couldn’t handle them simultaneously which inadvertently further stressed the scale. I also found the use of ‘just’ very interesting and thought that it did a decent job of stressing one aspect of the heritage of some of the modern countries which had slave vessels set sail from ports now found in their countries.

The visualisation allows visual comparisons of trade by phases, years, and events on an impactful, though superficial levelL e.g. the Caribbean taking over Brazil in terms of destination, US independence perhaps being a stimulus for this, UK abolition of slavery, etc. The ability track individual vessels and to then read about them is more engaging and impactful than searching through a spreadsheet.

I do think that the visualisation would have been more effective without the modern borders and would have been more sound had it had the old and modern names of the ports from which they set sail, rather than being so explicitly aimed to persuade a modern audience but that is only my preference. I think it also would have been useful to have some bookmarks on the timeline to give context and to show if slave trade did or did not respond to them, e.g. this is the historical timeline of events that you all know from school and now this is the one we are presenting to you in this visualisation. I also agree that highlighting certain flows over others to give interpretation would be useful, but perhaps this would be information overload compared to the purity of current visualisation.

**Comment by SePoQueR** [comment]
Hi, it's Simona. 
In response to "Age at Death in Roman Cyrenaica". 

1.	What cognitive and/or affective effect does this visualization have on you as a viewer/reader?
I think that both the graphic and diagram help to get an idea of the phenomenon at glance, as well as making it more objective. In other words, the psychological/emotional impact of a topic like death is partially obliterated by the graphic materialisation of that as data.

2.	How do you think that effect differs from reading the same data in other forms (e.g. as text or in a spreadsheet)?
As mentioned, through a quick glance you can gather the most significant information, whereas if it had been plain text, or even a spreadsheet, a reader should have gone through it to find the data that they were looking for.

3.	Can you imagine other ways this data could be visualised that would be more/less effective?
I feel the pie chart is not super clear as it includes too many slices. I’d probably add one or two line graphs showing how death rate falls in a specific age, and another showing how it develops across different areas.

4.	What do you imagine is the intent of the creator of the visualisation by presenting the data in this way? 
Clarity enhancement; underscoring some peculiarities: e.g. it strikes the hole in the first graph between 90 and 98.

**Comment by soneill-language-arts** [comment]
Hi, it's Sarah,

Re. Simona's comments on 'Age at Death in Roman Cyrenaica'

I agree with your comments Simona. It also struck me that there seem to be spikes in the death-rate every 10 years, which made me wonder whether age at death tended to be rounded up or down to the nearest ten for some reason.

I also thought that the charts were clearly aimed at other scholars with knowledge of the field. As a layperson myself, I would have probably benefitted from some contextualisation of the terms being used.

**Comment by kroncolleen** [comment]
Hi Sarah and Simona, 
Following up on your comments about the spikes every 10 years --> I personally wondered if it might be more helpful for the graph to contain some sort of "bins" of significant age ranges. So, I'm not sure how important it is to know that more people died at age 40 than age 41, as opposed to 40-45, 35-40, etc. (I'm also guessing you are right, Sarah, that 40 is a rounding convention rather than something precisely known.) On the up side, the graph made us ask these questions, so maybe it served its purpose!
