### ISSUE TITLE
Data Visualisation programmes not covered

### ISSUE THREAD

**Issue by SaraBorrello** [SASDigitalHumanitiesTraining/Visualisation#19]
Good morning all,
thank you for running the Data Visualisation course - I learnt a great deal!
Could you please list here the visualisation programmes we have not covered in our course, i.e. the ones Jonathan mentioned at the end of our last class? I just recall GIS. I am particularly - but not only - interested in network analysis programmes.
Many thanks!

**Comment by jonathanblaney** [comment]
Hi @SaraBorrello 

Glad you found the course useful!

The main one people in the Humanities use for networks is Gephi, which is free and cross-platform. If you haven't used it before I would definitely recommend starting with a very small network, because there are many options and it can quickly get confusing when you're starting out. There are other programs with more of a science or social science orientation and, from what I've heard, they are more difficult to get to grips with than Gephi.

In terms of GIS I would suggest QGIS, which has become a full-featured and free alternative to expensive programmes such as ArcGIS. I'm no expert at all in GIS but people who do know about it think QGIS is very good.

Another one we may have mentioned briefly is Palladio. I've only looked at it briefly but I think it can do a number of types of visualisation, including geographical.

For 3D visualisation there are lots of programs, from fairly intuitive web tools like SketchUp to highly complex and powerful desktop programs like Blender. I don't know enough to recommend one in particular but maybe @gabrielbodard will come in on this one.
